# This configuration is intended for development purpose, it's **your** responsibility to harden it for production

name: rpm-ddd-infra
services:
  postgres:
    image: postgres:18.1
    container_name: rpm-ddd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpm_ddd
      PGDATA: /var/lib/postgresql/data/pgdata
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10

