name: Run Code Quality Tools

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Cache Checkstyle cache-file
        id: cache-checkstyle
        uses: actions/cache@v5
        with:
          path: target/checkstyle-cachefile
          key:  ${{ runner.os }}-checkstyle
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Run Checkstyle (Fail on violations)
        run: mvn checkstyle:check -B

  pmd:
    name: PMD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Cache PMD cache-file
        id: cache-pmd
        uses: actions/cache@v5
        with:
          path: target/pmd/pmd.cache
          key: ${{ runner.os }}-pmd
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Run PMD (Fail on violations)
        run: mvn pmd:check -B
